import { ComponentMeta } from '../store/types';

export const componentRegistry: Record<string, ComponentMeta> = {
  Section: {
    type: 'Section',
    label: 'Section',
    icon: 'Layout',
    defaultProps: {},
    defaultStyles: {
      display: 'block',
      width: '100%',
      paddingTop: '5%',
      paddingBottom: '5%',
    },
    propsDefinition: {},
  },
  Box: {
    type: 'Box',
    label: 'Box',
    icon: 'Square',
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      padding: '16px',
      gap: '8px',
      backgroundColor: 'hsl(var(--muted))',
      borderRadius: '8px',
      minHeight: '100px',
    },
    propsDefinition: {},
  },
  Container: {
    type: 'Container',
    label: 'Container',
    icon: 'Container',
    defaultProps: {
      containerType: 'container',
    },
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      padding: '16px',
      gap: '8px',
      minHeight: '100px',
    },
    propsDefinition: {
      containerType: {
        type: 'select',
        label: 'Container Type',
        control: 'select',
        options: ['container', 'container-sm', 'container-md', 'container-lg', 'container-xl', 'container-xxl', 'container-fluid'],
        defaultValue: 'container',
      },
    },
  },
  Text: {
    type: 'Text',
    label: 'Text',
    icon: 'Type',
    defaultProps: {
      children: 'The text you can edit',
    },
    defaultStyles: {
      fontSize: '16px',
      lineHeight: '1.5',
      color: 'hsl(var(--foreground))',
    },
    propsDefinition: {
      children: {
        type: 'string',
        label: 'Content',
        control: 'textarea',
        defaultValue: 'Edit this text',
      },
    },
  },
  Heading: {
    type: 'Heading',
    label: 'Heading',
    icon: 'Heading',
    defaultProps: {
      level: 'h2',
      children: 'The future of AI-first hyper-personalized Websites.',
    },
    defaultStyles: {
      fontSize: '48px',
      fontWeight: '700',
      lineHeight: '1.2',
      color: 'hsl(var(--foreground))',
    },
    propsDefinition: {
      level: {
        type: 'select',
        label: 'Level',
        control: 'select',
        options: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
        defaultValue: 'h2',
      },
      children: {
        type: 'string',
        label: 'Content',
        control: 'textarea',
        defaultValue: 'Heading',
      },
    },
  },
  Button: {
    type: 'Button',
    label: 'Button',
    icon: 'MousePointerClick',
    defaultProps: {
      children: 'Button',
    },
    defaultStyles: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '4px',
      whiteSpace: 'nowrap',
      borderRadius: '4px',
      fontSize: '14px',
      fontWeight: '500',
      height: '32px',
      paddingLeft: '10px',
      paddingRight: '10px',
      backgroundColor: 'hsl(217, 91%, 60%)',
      color: 'hsl(0, 0%, 100%)',
      cursor: 'pointer',
      border: 'none',
      boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      transition: 'all 0.2s ease',
    },
    propsDefinition: {
      children: {
        type: 'string',
        label: 'Text',
        control: 'text',
        defaultValue: 'Button',
      },
    },
  },
  Image: {
    type: 'Image',
    label: 'Image',
    icon: 'Image',
    defaultProps: {
      src: 'https://via.placeholder.com/400x300',
      alt: 'Placeholder image',
    },
    defaultStyles: {
      width: '100%',
      height: 'auto',
      borderRadius: '8px',
    },
    propsDefinition: {
      src: {
        type: 'string',
        label: 'Source URL',
        control: 'text',
        defaultValue: 'https://via.placeholder.com/400x300',
      },
      alt: {
        type: 'string',
        label: 'Alt Text',
        control: 'text',
        defaultValue: 'Image description',
      },
    },
  },
  Link: {
    type: 'Link',
    label: 'Link',
    icon: 'Link',
    defaultProps: {
      href: '#',
      children: 'Link text',
    },
    defaultStyles: {
      color: 'hsl(var(--primary))',
      textDecoration: 'underline',
      cursor: 'pointer',
      fontSize: '14px',
      lineHeight: '1.5',
    },
    propsDefinition: {
      href: {
        type: 'string',
        label: 'URL',
        control: 'text',
        defaultValue: '#',
      },
      children: {
        type: 'string',
        label: 'Text',
        control: 'text',
        defaultValue: 'Link',
      },
    },
  },
  
  // Commonly Used Components
  Table: {
    type: 'Table',
    label: 'Table',
    icon: 'Table',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  NumberInput: {
    type: 'NumberInput',
    label: 'Number Input',
    icon: 'Hash',
    defaultProps: { placeholder: '0' },
    defaultStyles: {},
    propsDefinition: {},
  },
  TabbedContainer: {
    type: 'TabbedContainer',
    label: 'Tabbed Container',
    icon: 'PanelTop',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  MixedChart: {
    type: 'MixedChart',
    label: 'Mixed Chart',
    icon: 'BarChart3',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  KeyValue: {
    type: 'KeyValue',
    label: 'Key Value',
    icon: 'ListTree',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Navigation: {
    type: 'Navigation',
    label: 'Navigation',
    icon: 'Navigation',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  
  // Text Inputs Category
  EditableText: {
    type: 'EditableText',
    label: 'Editable Text',
    icon: 'PenLine',
    defaultProps: { placeholder: 'Edit text...' },
    defaultStyles: {},
    propsDefinition: {},
  },
  EditableTextArea: {
    type: 'EditableTextArea',
    label: 'Editable Text Area',
    icon: 'PenSquare',
    defaultProps: { placeholder: 'Edit text...' },
    defaultStyles: {},
    propsDefinition: {},
  },
  Email: {
    type: 'Email',
    label: 'Email',
    icon: 'AtSign',
    defaultProps: { placeholder: 'email@example.com' },
    defaultStyles: {},
    propsDefinition: {},
  },
  JSONEditor: {
    type: 'JSONEditor',
    label: 'JSON Editor',
    icon: 'Braces',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Password: {
    type: 'Password',
    label: 'Password',
    icon: 'KeyRound',
    defaultProps: { placeholder: 'Password' },
    defaultStyles: {},
    propsDefinition: {},
  },
  RichTextEditor: {
    type: 'RichTextEditor',
    label: 'Rich Text Editor',
    icon: 'Type',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  URL: {
    type: 'URL',
    label: 'URL',
    icon: 'Link2',
    defaultProps: { placeholder: 'https://' },
    defaultStyles: {},
    propsDefinition: {},
  },
  
  // Charts Category
  BarChart: {
    type: 'BarChart',
    label: 'Bar Chart',
    icon: 'BarChart4',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  BubbleChart: {
    type: 'BubbleChart',
    label: 'Bubble Chart',
    icon: 'Circle',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  FunnelChart: {
    type: 'FunnelChart',
    label: 'Funnel Chart',
    icon: 'TrendingDown',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  HeatMap: {
    type: 'HeatMap',
    label: 'Heat Map',
    icon: 'Grid3x3',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  LineChart: {
    type: 'LineChart',
    label: 'Line Chart',
    icon: 'LineChart',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  PieChart: {
    type: 'PieChart',
    label: 'Pie Chart',
    icon: 'PieChart',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  PlotlyJSONChart: {
    type: 'PlotlyJSONChart',
    label: 'Plotly JSON Chart',
    icon: 'Code2',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  SankeyChart: {
    type: 'SankeyChart',
    label: 'Sankey Chart',
    icon: 'GitBranch',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  ScatterChart: {
    type: 'ScatterChart',
    label: 'Scatter Chart',
    icon: 'Sparkles',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Sparkline: {
    type: 'Sparkline',
    label: 'Sparkline',
    icon: 'Activity',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  StackedBarChart: {
    type: 'StackedBarChart',
    label: 'Stacked Bar Chart',
    icon: 'BarChart2',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  SunburstChart: {
    type: 'SunburstChart',
    label: 'Sunburst Chart',
    icon: 'Sun',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Treemap: {
    type: 'Treemap',
    label: 'Treemap',
    icon: 'LayoutGrid',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  WaterfallChart: {
    type: 'WaterfallChart',
    label: 'Waterfall Chart',
    icon: 'Waves',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  
  // Presentation Category
  Alert: {
    type: 'Alert',
    label: 'Alert',
    icon: 'AlertCircle',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Avatar: {
    type: 'Avatar',
    label: 'Avatar',
    icon: 'User',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  AvatarGroup: {
    type: 'AvatarGroup',
    label: 'Avatar Group',
    icon: 'Users',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Calendar: {
    type: 'Calendar',
    label: 'Calendar',
    icon: 'Calendar',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  CircularImage: {
    type: 'CircularImage',
    label: 'Circular Image',
    icon: 'CircleUser',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Divider: {
    type: 'Divider',
    label: 'Divider',
    icon: 'Minus',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  EventList: {
    type: 'EventList',
    label: 'Event List',
    icon: 'ListOrdered',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Icon: {
    type: 'Icon',
    label: 'Icon',
    icon: 'Smile',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  IconText: {
    type: 'IconText',
    label: 'Icon Text',
    icon: 'ALargeSmall',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  ImageGrid: {
    type: 'ImageGrid',
    label: 'Image Grid',
    icon: 'Images',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  PDF: {
    type: 'PDF',
    label: 'PDF',
    icon: 'FileText',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  ProgressBar: {
    type: 'ProgressBar',
    label: 'Progress Bar',
    icon: 'Loader',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  ProgressCircle: {
    type: 'ProgressCircle',
    label: 'Progress Circle',
    icon: 'Loader2',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  QRCode: {
    type: 'QRCode',
    label: 'QR Code',
    icon: 'QrCode',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Spacer: {
    type: 'Spacer',
    label: 'Spacer',
    icon: 'Space',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Statistic: {
    type: 'Statistic',
    label: 'Statistic',
    icon: 'TrendingUp',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Status: {
    type: 'Status',
    label: 'Status',
    icon: 'MapPin',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Tags: {
    type: 'Tags',
    label: 'Tags',
    icon: 'Tags',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Timeline: {
    type: 'Timeline',
    label: 'Timeline',
    icon: 'Timeline',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Video: {
    type: 'Video',
    label: 'Video',
    icon: 'Video',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  
  // Forms Category (already defined above, keeping originals)
  Form: {
    type: 'Form',
    label: 'Form',
    icon: 'FileText',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  InputLabel: {
    type: 'InputLabel',
    label: 'Input Label',
    icon: 'Tag',
    defaultProps: {
      children: 'Label',
    },
    defaultStyles: {},
    propsDefinition: {
      children: {
        type: 'string',
        label: 'Text',
        control: 'text',
        defaultValue: 'Label',
      },
    },
  },
  TextInput: {
    type: 'TextInput',
    label: 'Text Input',
    icon: 'TextCursor',
    defaultProps: {
      placeholder: 'Enter text...',
    },
    defaultStyles: {},
    propsDefinition: {
      placeholder: {
        type: 'string',
        label: 'Placeholder',
        control: 'text',
        defaultValue: 'Enter text...',
      },
    },
  },
  TextArea: {
    type: 'TextArea',
    label: 'Text Area',
    icon: 'AlignLeft',
    defaultProps: {
      placeholder: 'Enter text...',
    },
    defaultStyles: {},
    propsDefinition: {
      placeholder: {
        type: 'string',
        label: 'Placeholder',
        control: 'text',
        defaultValue: 'Enter text...',
      },
    },
  },
  Select: {
    type: 'Select',
    label: 'Select',
    icon: 'ChevronDown',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Radio: {
    type: 'Radio',
    label: 'Radio',
    icon: 'Circle',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Checkbox: {
    type: 'Checkbox',
    label: 'Checkbox',
    icon: 'CheckSquare',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  
  // Localization Category
  Time: {
    type: 'Time',
    label: 'Time',
    icon: 'Clock',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  
  // Radix Category
  Sheet: {
    type: 'Sheet',
    label: 'Sheet',
    icon: 'PanelRight',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  NavigationMenu: {
    type: 'NavigationMenu',
    label: 'Navigation Menu',
    icon: 'Menu',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Tabs: {
    type: 'Tabs',
    label: 'Tabs',
    icon: 'Tabs',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Accordion: {
    type: 'Accordion',
    label: 'Accordion',
    icon: 'ChevronRight',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Dialog: {
    type: 'Dialog',
    label: 'Dialog',
    icon: 'MessageSquare',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Collapsible: {
    type: 'Collapsible',
    label: 'Collapsible',
    icon: 'ChevronsUpDown',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Popover: {
    type: 'Popover',
    label: 'Popover',
    icon: 'MessageCircle',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Tooltip: {
    type: 'Tooltip',
    label: 'Tooltip',
    icon: 'Info',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Switch: {
    type: 'Switch',
    label: 'Switch',
    icon: 'ToggleLeft',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  RadioGroup: {
    type: 'RadioGroup',
    label: 'Radio Group',
    icon: 'CircleDot',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Label: {
    type: 'Label',
    label: 'Label',
    icon: 'Tag',
    defaultProps: { children: 'Label' },
    defaultStyles: {},
    propsDefinition: {},
  },
};
