import { ComponentMeta } from '../store/types';

export const componentRegistry: Record<string, ComponentMeta> = {
  Section: {
    type: 'Section',
    label: 'Section',
    icon: 'Layout',
    defaultProps: {},
    defaultStyles: {
      display: 'block',
      width: '100%',
      paddingTop: '5%',
      paddingBottom: '5%',
    },
    propsDefinition: {},
  },
  Box: {
    type: 'Box',
    label: 'Box',
    icon: 'Square',
    defaultProps: {},
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      padding: '16px',
      gap: '8px',
      backgroundColor: 'hsl(var(--muted))',
      borderRadius: '8px',
      minHeight: '100px',
    },
    propsDefinition: {},
  },
  Container: {
    type: 'Container',
    label: 'Container',
    icon: 'Container',
    defaultProps: {
      containerType: 'container',
    },
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      padding: '16px',
      gap: '8px',
      minHeight: '100px',
    },
    propsDefinition: {
      containerType: {
        type: 'select',
        label: 'Container Type',
        control: 'select',
        options: ['container', 'container-sm', 'container-md', 'container-lg', 'container-xl', 'container-xxl', 'container-fluid'],
        defaultValue: 'container',
      },
    },
  },
  Text: {
    type: 'Text',
    label: 'Text',
    icon: 'Type',
    defaultProps: {
      children: 'The text you can edit',
    },
    defaultStyles: {
      fontSize: '16px',
      lineHeight: '1.5',
      color: 'hsl(var(--foreground))',
    },
    propsDefinition: {
      children: {
        type: 'string',
        label: 'Content',
        control: 'textarea',
        defaultValue: 'Edit this text',
      },
    },
  },
  Heading: {
    type: 'Heading',
    label: 'Heading',
    icon: 'Heading',
    defaultProps: {
      level: 'h2',
      children: 'The future of AI-first hyper-personalized Websites.',
    },
    defaultStyles: {
      fontSize: '48px',
      fontWeight: '700',
      lineHeight: '1.2',
      color: 'hsl(var(--foreground))',
    },
    propsDefinition: {
      level: {
        type: 'select',
        label: 'Level',
        control: 'select',
        options: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
        defaultValue: 'h2',
      },
      children: {
        type: 'string',
        label: 'Content',
        control: 'textarea',
        defaultValue: 'Heading',
      },
    },
  },
  Button: {
    type: 'Button',
    label: 'Button',
    icon: 'MousePointerClick',
    defaultProps: {
      children: 'Button',
    },
    defaultStyles: {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '4px',
      whiteSpace: 'nowrap',
      borderRadius: '4px',
      fontSize: '14px',
      fontWeight: '500',
      height: '32px',
      paddingLeft: '10px',
      paddingRight: '10px',
      backgroundColor: 'hsl(217, 91%, 60%)',
      color: 'hsl(0, 0%, 100%)',
      cursor: 'pointer',
      border: 'none',
      boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      transition: 'all 0.2s ease',
    },
    propsDefinition: {
      children: {
        type: 'string',
        label: 'Text',
        control: 'text',
        defaultValue: 'Button',
      },
    },
  },
  Image: {
    type: 'Image',
    label: 'Image',
    icon: 'Image',
    defaultProps: {
      src: 'https://via.placeholder.com/400x300',
      alt: 'Placeholder image',
    },
    defaultStyles: {
      width: '100%',
      height: 'auto',
      borderRadius: '8px',
    },
    propsDefinition: {
      src: {
        type: 'string',
        label: 'Source URL',
        control: 'text',
        defaultValue: 'https://via.placeholder.com/400x300',
      },
      alt: {
        type: 'string',
        label: 'Alt Text',
        control: 'text',
        defaultValue: 'Image description',
      },
    },
  },
  Link: {
    type: 'Link',
    label: 'Link',
    icon: 'Link',
    defaultProps: {
      href: '#',
      children: 'Link text',
    },
    defaultStyles: {
      color: 'hsl(var(--primary))',
      textDecoration: 'underline',
      cursor: 'pointer',
      fontSize: '14px',
      lineHeight: '1.5',
    },
    propsDefinition: {
      href: {
        type: 'string',
        label: 'URL',
        control: 'text',
        defaultValue: '#',
      },
      children: {
        type: 'string',
        label: 'Text',
        control: 'text',
        defaultValue: 'Link',
      },
    },
  },
  // Forms Category
  Form: {
    type: 'Form',
    label: 'Form',
    icon: 'FileText',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  InputLabel: {
    type: 'InputLabel',
    label: 'Input Label',
    icon: 'Tag',
    defaultProps: {
      children: 'Label',
    },
    defaultStyles: {},
    propsDefinition: {
      children: {
        type: 'string',
        label: 'Text',
        control: 'text',
        defaultValue: 'Label',
      },
    },
  },
  TextInput: {
    type: 'TextInput',
    label: 'Text Input',
    icon: 'TextCursor',
    defaultProps: {
      placeholder: 'Enter text...',
    },
    defaultStyles: {},
    propsDefinition: {
      placeholder: {
        type: 'string',
        label: 'Placeholder',
        control: 'text',
        defaultValue: 'Enter text...',
      },
    },
  },
  TextArea: {
    type: 'TextArea',
    label: 'Text Area',
    icon: 'AlignLeft',
    defaultProps: {
      placeholder: 'Enter text...',
    },
    defaultStyles: {},
    propsDefinition: {
      placeholder: {
        type: 'string',
        label: 'Placeholder',
        control: 'text',
        defaultValue: 'Enter text...',
      },
    },
  },
  Select: {
    type: 'Select',
    label: 'Select',
    icon: 'ChevronDown',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Radio: {
    type: 'Radio',
    label: 'Radio',
    icon: 'Circle',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Checkbox: {
    type: 'Checkbox',
    label: 'Checkbox',
    icon: 'CheckSquare',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  // Localization Category
  Time: {
    type: 'Time',
    label: 'Time',
    icon: 'Clock',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  // Radix Category
  Sheet: {
    type: 'Sheet',
    label: 'Sheet',
    icon: 'PanelRight',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  NavigationMenu: {
    type: 'NavigationMenu',
    label: 'Navigation Menu',
    icon: 'Menu',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Tabs: {
    type: 'Tabs',
    label: 'Tabs',
    icon: 'Tabs',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Accordion: {
    type: 'Accordion',
    label: 'Accordion',
    icon: 'ChevronRight',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Dialog: {
    type: 'Dialog',
    label: 'Dialog',
    icon: 'MessageSquare',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Collapsible: {
    type: 'Collapsible',
    label: 'Collapsible',
    icon: 'ChevronsUpDown',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Popover: {
    type: 'Popover',
    label: 'Popover',
    icon: 'MessageCircle',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Tooltip: {
    type: 'Tooltip',
    label: 'Tooltip',
    icon: 'Info',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  Switch: {
    type: 'Switch',
    label: 'Switch',
    icon: 'ToggleLeft',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
  RadioGroup: {
    type: 'RadioGroup',
    label: 'Radio Group',
    icon: 'CircleDot',
    defaultProps: {},
    defaultStyles: {},
    propsDefinition: {},
  },
};
